package com.teuskim.takefive.common;

/**
 * COM과 USER의 패턴 정의
 * C=>COM, U=>USER, N=>none
 */
public enum Pattern {
	COM_CCCCC,
	COM_NCCCCN,
	COM_UCCCCN, COM_NCCCCU,
	COM_CNCCC, COM_CCNCC, COM_CCCNC,
	COM_NNCCCNN, 
	COM_UNCCCNN, COM_NNCCCNU, COM_NCNCCN, COM_NCCNCN,
	COM_UCCCNN, COM_NNCCCU, COM_UCNCCN, COM_NCNCCU, COM_UCCNCN, COM_NCCNCU,
	COM_NNCCNN, COM_NCNCN,
	COM_UNCCNN, COM_NNCCNU,
	COM_UCCNNN, COM_NNNCCU,
	
	USER_UUUUU,
	USER_NUUUUN,
	USER_CUUUUN, USER_NUUUUC,
	USER_UNUUU, USER_UUNUU, USER_UUUNU,
	USER_NNUUUNN,
	USER_CNUUUNN, USER_NNUUUNC, USER_NUNUUN, USER_NUUNUN,
	USER_CUUUNN, USER_NNUUUC, USER_CUNUUN, USER_NUNUUC, USER_CUUNUN, USER_NUUNUC,
	USER_NNUUNN, USER_NUNUN,
	USER_CNUUNN, USER_NNUUNC,
	USER_CUUNNN, USER_NNNUUC
}
